### ISSUE TITLE
Binary fields values are broken by default

### ISSUE THREAD

**Issue by denis-aes** [gheeres/node-activedirectory#103]
ThumbnailPhoto - is default field in Active Directory, where users photos are stored
https://support.microsoft.com/en-us/kb/292029

activedirectory library by default - converts all buffers to strings.

This brokes binary fields values. To replace string with original binary buffer - I have to add entry parser
```javascript
entryParser: function(entry, raw, callback){
    if (raw.hasOwnProperty("thumbnailPhoto")){
        entry.thumbnailPhoto = raw.thumbnailPhoto;
    }
}
```

Would be great to
0. at least notice this in documentation
1. make some king of flag or separate list of binary fields that should not be converted to strings

**Comment by gheeres** [comment]
>activedirectory library by default - converts all buffers to strings.

Technically no, the ldapjs library converts buffers to strings.

> at least notice this in documentation

This is noted in the documentation under the section labeled "Custom Entry Parsing".

```
if you want to manipulate the search entry in a different way or perhaps 
augment the search result with additional data, you can pass a custom parser. 
This is useful, for example, in case you want to change the objectSid or GUID 
which are binary values.
```

Please send a pull request to improve and update the documentation with additional examples and/or clarification.

> make some kind of flag or separate list of binary fields that should not be converted to strings

This is an edge case scenario that the entryParser option was added to handle. The entryParser can be configured globally or on a per call basis. Is that solution not meeting your needs?

One problem with maintaining a list of binary fields is that it is not a truly static list. The Active Directory schema can be extended and customized per domain / installation, so this list would need to be configurable via the config object used at object creation.

Please submit a pull request for review.

**Comment by gheeres** [comment]
Closing due to lack of response / feedback. Please reply or submit a pull request to reopen discussion.
