### ISSUE TITLE
Can Authenticate but Not Lookup

### ISSUE THREAD

**Issue by ybitso** [gheeres/node-activedirectory#104]
Hi,

I need some guidance on this. I am able to successfully authenticate numerous users to the AD; however, if I attempt to do find, findUser, userExists (all with using the sample code), I get 'undefined'

Any ideas how to troubleshoot this?  

Thanks

**Comment by gheeres** [comment]
See the following issue/question: 

https://github.com/gheeres/node-activedirectory/issues/96

I believe you have a configuration problem.

**Comment by ybitso** [comment]
Thanks, but using that code from that posting and ensuring my configuration, I don't get that error, I i get false for the exists, no error ; i tried both ad.userExists(shortname,..) and ad.userExists(shortname@domain.com, ...)

I do have dollar signs in the password, and did try to escape them with no luck.  

Also, for userExists, i tried another user as well as the same user in the bindings, they are all false.  Even the user I am currently logged into my system with on the domain, shows up as false

**Comment by gheeres** [comment]
Check your configuration that you provide when calling 'new ActiveDirectory(config)'. You MUST have a valid username and password configured. This is NOT the username/password of the currently logged in user. This is anot dedicated account / user that can query and read active directory. It's the account used for account lookup and search options.  This user name MUST be a userPrincipalName (I.e user@domain.com). You cannot use the sAMAccountName or NTLOGIN for this.

If you still have problems you're going to need to post sample code, including you configuration object.

**Comment by ybitso** [comment]
```
        var config = {
            url: 'LDAP://servername.domain.com',
            baseDN: 'cn=users,dc=domain,dc=com',
            username: 'serviceaccount@domain.com',
            password: 'password' 
        }
        var ad = new ActiveDirectory(config);
        var userPrincipalName  = 'username@domain.com';
        var username = 'myusername'
        var userpass = 'password2'

        //the below auth works
        ad.authenticate(userPrincipalName, userpass , function(err, auth) {
            if (err) {
                console.error('ERROR: '+JSON.stringify(err));
            }
            else {
                if (auth) {
                    console.log('Good');
                }
                else {
                    console.error('Authentication failed!');
                }
            }
        });

        //the below userExist returns:
        //myusername exists: false
        //tried both username and userPrincipalName
        ad.userExists(userPrincipalName, function (err, exists) {
            if (err) {
                console.log('ERROR: ' + JSON.stringify(err));
                return;
            }

            console.log(username + ' exists: ' + exists);
        })
```

In the config, i tried both a service account and a normal user account.  both have lookup (at least the user account should), but either case, I am getting the same exists = false

Any trace i can enable to see whats going on?

**Comment by gheeres** [comment]
Try using the [findUser()](https://github.com/gheeres/node-activedirectory#findUser) method for your testing. The userExists is just a convenience wrapper.

Yes, there is a logging option available which uses Bunyan. To configure bunyan, change your AD config to include a 'logging' property:

```javascript
var adConfig = {
    url: url,
    baseDN: baseDN,
    username: username,
    password: password,
    logging: {
      name: 'ActiveDirectory',
      streams: [
        { level: 'debug',
          stream: process.stdout }
      ]
    }
  }
```

**Comment by ybitso** [comment]
Found my error

The basedn i had cn=users should have been ou=users
I had cn=users in my .net code and it works, been using that for a while, so I used the same (probably some tight iis integration to AD)

The debug helped as I went through everything outputted.  If I put a an invalid basedn, it throws error, which it should, but putting that basedn i was using connects, but throws the undefined error i was getting.(btw, I used JXplorer for further testing)

Thanks for the help
