### ISSUE TITLE
Error when running samples

### ISSUE THREAD

**Issue by zalym** [gheeres/node-activedirectory#105]
Hi,

I used the code given in the samples, but get the following error, inspite of having the correct credentials.

ERROR: {"dn":"","code":49,"name":"InvalidCredentialsError","message":"80090308:
LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\u0
000"}

Is there anything else that I need to configure?

Thanks

**Comment by gheeres** [comment]
What active directory method are you calling?

The username in your configuration MUST be a fully qualified username (userPrincipalName). Instead of just 'username', it must be 'username@domain.com' where 'domain.com' represents your active directory domain.

**Comment by zalym** [comment]
Thanks!  That worked!

**Comment by zalym** [comment]
I am able to authenticate now, but am having issues whenever I am trying the other methods.  

I tried doing the following methods:getMembershipForUser, findUser, find...  but keep getting the same error:
(err.code=10)
    ReferralError: 0000202B: RefErr: DSID-031007EF, data 0, 1 access points
        ref 1: 'ourdomain.com'

Appreciate if you could give me some pointers on this.  I am sure it is my ignorance of how the ldap is referenced.

**Comment by zalym** [comment]
Closing it again!.  I referred to the GlobalCatalog and that worked!
