### ISSUE TITLE
Exception handling for ActiveDirectory

### ISSUE THREAD

**Issue by email2vimalraj** [gheeres/node-activedirectory#108]
I have my code like this:

	var ActiveDirectory = require('activedirectory');

	var config = {
		url: 'ldap://url',
		baseDN: 'dc=company,dc=com',
		username: 'abc@example.com',
		password: 'abc'		// Invalid password
	};

	var ad = new ActiveDirectory(config);

	ad.authenticate(
		'abc@example.com', 
		'def', 	// Valid or invalid password
		function(err, auth) {
			if (err) {
				console.log('ERROR: '+JSON.stringify(err));
				return;
			}

			if (auth) {
				console.log('Authenticated!');
			} else {
				console.log('Authentication failed!');
			}
	});

I was expecting it would throw an error since I pass invalid password in the config. But it just waiting for something. Am I making any mistake here?

**Comment by gheeres** [comment]
I just added a test case for what you reported:

448212de0c2938b248dde7f7fae8b3c4ebd13457

I am getting the expected InvalidCredentialsError exception in the err parameter.

```javascript
    it('should throw an InvalidCredentialsError exception if the username/password are incorrect.', function(done) {
      var ad = new ActiveDirectory(_.extend({}, config, {
        password: 'TheWrongPassword!',
        username: 'AnInvalidUsername',
      }));
      ad.findUser('unknown', function(err, user) {
        assert.notEqual(null, err);
        assert.equal(err.name, 'InvalidCredentialsError');
        done();
      });
    });
```

The username/password that you provide in the configuration (config.js) is used for lookup of user information. It's the username that is used to search your active directory and typically can see "everything". Every function **EXCEPT** [authenticate()](https://github.com/gheeres/node-activedirectory/#authenticate) uses that username/password for their execution.

For [authenticate()](https://github.com/gheeres/node-activedirectory/#authenticate), the *auth* flag will be set to false if authentication fails. In addition, the err parameter will also be set. See the tests for additional clarification: https://github.com/gheeres/node-activedirectory/blob/master/test/authenticate.js

**Comment by email2vimalraj** [comment]
Thanks @gheeres. This is working like a charm.
