### ISSUE TITLE
Use sAMAccountName for bind

### ISSUE THREAD

**Issue by Goober68** [gheeres/node-activedirectory#111]
I am working on a project where I am using AD as the authentication store, but don't have the DN of the users, only the sAMAccountName.  I would like to be able to verify their credentials by doing a simple bind using their sAMAccountName directly.  Currently I have to bind with a known DN, then do a lookup of the user's DN using their sAMAccountName, then bind with the user's found DN in order to verify their credentials.

**Comment by gheeres** [comment]
Sorry. I'm not sure I follow you?

You can do a bind with a userPrincipalName. Change the sAMAccountName to a userPrincipalName (typically by appending the domain suffix).

With the ActiveDirectory object you can authenticate a user using the [authenticate()](https://github.com/gheeres/node-activedirectory#authenticate) method. If only using the [authenticate()](https://github.com/gheeres/node-activedirectory#authenticate) method (i.e. you're not doing user information or group lookup), you don't even need to have the username & password specified in the configuration object. 

Keep in mind that the provided username must be a userPrincipalName. 

If you still have problems or questions, please provide some sample code, etc.

**Comment by Goober68** [comment]
Thanks - switching to userPrincipalName worked, I didn't realize that the authenticate would take a userPrincipalName, appending the domain suffix to the sAMAccountName allowed me to bind directly to AD.
