### ISSUE TITLE
bug in ldapjs 0.7.1

### ISSUE THREAD

**Issue by dmarkhas** [gheeres/node-activedirectory#116]
ldapjs has a bug in 0.7.1 (which is a dependency in package.json) which breaks TLS:
https://github.com/mcavage/node-ldapjs/issues/256

Can you update package.json to use ldapjs 0.8?

**Comment by gheeres** [comment]
There is no official npm ldapjs 0.8 release. The package.json is set as follows:

```javascript
  "dependencies": {
    "async": ">= 0.1.22",
    "bunyan": ">= 1.3.5",
    "ldapjs": ">= 0.7.1",
    "underscore": ">= 1.4.3"
  },
```

That should pull the latest version of ldap (1.0.0).
NPM Versioning: [semver](https://docs.npmjs.com/misc/semver)
