### ISSUE TITLE
How connect to Global Catalog?

### ISSUE THREAD

**Issue by Churanos** [gheeres/node-activedirectory#117]
Hi there,

is it possible to connect to a global catalog?
For example: `ldap://my.domain:3268`
This works in my gitBlit installation, but not with node-activedirctory.

Have you any idea how can i solve this?

**Comment by gheeres** [comment]
Yes. Just specify the same url in your config. Tested. Working.

```javascript
var config = {
  url: 'ldap://my.domain:3268',
  baseDN: 'dc=my,dc=domain',
  username: 'yourlookupusername',
  password: 'yourlookupusernamepassword'
};
var ad = new ActiveDirectory(config);
```

Note that port 3268 is global catalog for LDAP. 3269 is the global catalog port for LDAPS (SSL).
