### ISSUE TITLE
Custom Attributes causing findUsers query to error

### ISSUE THREAD

**Issue by chris-neely** [gheeres/node-activedirectory#129]
I believe there is an issue when using the attributes options to try and define what attributes the function should return.  Maybe I just have some syntax off here or something but as far as I can tell the below script should work.

Using the below script to return results from findUsers (only with my ldap details entered) the result returns:

> ERROR: {}
> Authenticated!

If i remove the 'attributes' array from the config options it works perfectly and returns the users info.  I am trying to return lastLogonTimestamp for a script.

```
var ActiveDirectory = require('activedirectory');

var ad = new ActiveDirectory({
    url: dirUrl,
    baseDN: baseDN,
    username: username,
    password: password,
    attributes: {
        user: [ 'sAMAccountName' ],
        group: [ 'objectCategory' ]
    }
});


ad.authenticate(username, password, function (err, auth) {
    if (err) {
        console.log('ERROR: ' + JSON.stringify(err));
        return;
    }
    if (auth) {
        console.log('Authenticated!');
    }
    else {
        console.log('Authentication failed!');
    }
});


var query = 'cn=*Chris*';


ad.findUsers(query, true, function (err, users) {
    if (err) {
        console.log('ERROR: ' + JSON.stringify(err));
        return;
    }

    if ((!users) || (users.length == 0)) console.log('No users found.');
    else {
        console.log('findUsers: ' + JSON.stringify(users));
    }
});
```

**Comment by gheeres** [comment]
Node.js is asynchronous. The ad.authenticate() method will start the execution and pass in a callback to get invoked "after" work has been completed. The main thread continues processing the next line without waiting for the previous call to come back.

I'm not sure why you have an authenticate() followed by a findUsers(). What are you trying to accomplish / do?

**Comment by chris-neely** [comment]
Yes, I realize that and I only had that there for testing initially to confirm it was authenticating and just forgot to remove it.  Even if I remove ad.authenticate I still receive the same result as in my original post.

If I change the code to this it does pull back all attributes but it does it for all users.  Is there a way to use a query inside of the opts parameter?


```
var ActiveDirectory = require('activedirectory');

var ad = new ActiveDirectory({
    url: dirUrl,
    baseDN: baseDN,
    username: username,
    password: password
});


var opts = {
    attributes: [ '*' ],
};

ad.findUsers(opts, true, function (err, users) {
    if (err) {
        console.log('ERROR: ' + JSON.stringify(err));
        return;
    }

    if ((!users) || (users.length == 0)) console.log('No users found.');
    else {
        console.log('findUsers: ' + JSON.stringify(users));
        console.log(users[0].lastLogonTimeStamp);
    }
});
```

**Comment by gheeres** [comment]
There are some required attributes that MUST be included, especially when requesting that groups are returned. This should be handled internally but automatically appending those necessary attributes in if they are omitted. I'm going to guess those attributes aren't getting updated correctly. 

Please enable logging and inspect the operation / results:

##### Enable Logging
To see more details about what is going on, you can also enable logging within your AD configuration object which can then be piped through the bunyan utility.

```javascript
var config = {
  url: 'ldap://dc.domain.com',
  baseDN: 'dc=domain,dc=com',
  username: 'searchuser@domain.com',
  password: 'searchuser-password',
  logging: {
    name: 'ActiveDirectory',
    streams: [
      { level: 'error',
        stream: process.stdout }
    ]
  }
};
var ad = new ActiveDirectory(config);
```

And then to parse the log output, you'll pipe the output through bunyan:

```
node yourfile.js | bunyan
```

**Comment by chris-neely** [comment]
Thanks for the reply George.  I'll give that a shot and see what the results are.

**Comment by chris-neely** [comment]
Ok, setting the boolean value for 'returning group membership' to false resolved the error.  I understand this wasn't an issue with the module but you may want to update the documentation for findUsers.

I've copied the documentation to this post because it does not list or explain what this boolean value does under the arguments section for findUsers .  The only way I found this was by looking deeper in the modules and reading your above post.  It may be helpful for others if it were documented on the front page with the other examples.

> findUsers(opts, callback)
> 
> Perform a generic search for users that match the specified filter. The default LDAP filter for users is specified as (&(|(objectClass=user)(objectClass=person))(!(objectClass=computer))(!(objectClass=group)))
> 
> Arguments
> 
> opts - Optional parameters to extend or override functionality. See optional parameters. If only a string is provided, then the string is assumed to be an LDAP filter that will be appended as the last parameter in the default LDAP filter.
> callback - The callback to execute when completed. callback(err: {Object}, users: {Array[User]})
> Example

```
var query = 'cn=*George*';

var ad = new ActiveDirectory(config);
ad.findUsers(query, true, function(err, users) {
  if (err) {
    console.log('ERROR: ' +JSON.stringify(err));
    return;
  }

  if ((! users) || (users.length == 0)) console.log('No users found.');
  else {
    console.log('findUsers: '+JSON.stringify(users));
  }
});
```

**Comment by chris-neely** [comment]
Thank you for your help and time George.

**Comment by gheeres** [comment]
The "true" parameter is a left over from an older version of the API that was deprecated. Thanks for pointing out the documentation inconsistency.
