### ISSUE TITLE
Support multiple AD domains

### ISSUE THREAD

**Issue by GiladShoham** [gheeres/node-activedirectory#131]
Hi,
I have some customers who need our app to support multiple AD domains.
for example if i search for a user, they want to search in all the domains, same for login and so on.
Is there anything internal which make this possible or i need to write some wrapper who run any function against each domain?

Thx a lot:)

**Comment by gheeres** [comment]
If they are part of a forest with referrals, then it should be able to authenticate. If however, they are separate domains then you'll need to write your own wrapper.

**Comment by GiladShoham** [comment]
Thx!
