### ISSUE TITLE
ERROR: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"} even after cert import locally done

### ISSUE THREAD

**Issue by chakrapani123** [gheeres/node-activedirectory#146]
Index.js content:

```javascript
var ActiveDirectory = require('activedirectory');
var config = { url: 'ldaps://example.com:636',
               baseDN: 'OU=Service Accounts,OU=XXX,OU=XXX,DC=xXX,DC=XXXX,DC=XXX',
               username: 'abcdefff',
               password: 'BBBBYYY'

                }
var ad = new ActiveDirectory(config);
var username = 'use@domain.com'; 
var password = 'secretpass';

ad.authenticate(username, password, function(err, auth) {
  if (err) {
    console.log('ERROR: '+JSON.stringify(err));
    return;
  }

  if (auth) {
    console.log('Authenticated!');
  }
  else {
    console.log('Authentication failed!');
  }
});
```

i have tried it locally using ldapsearch CLI and it works fine.

**Comment by gheeres** [comment]
Are you running on a Linux, Mac or Windows host? If running on Windows, see the following related blog post I created:  http://blog.heeresonline.com/2014/05/nodejs-cert_untrusted-error/

The fact that ldapsearch works isn't really relevant. The ldapsearch cli can be configured via the ldap.conf file to ignore certificate problems / errors.

**Comment by chakrapani123** [comment]
I am running on Mac . I did check this blog prior to opening this issue and followed the steps to add the cert and even after cert addition ran into same issues. 

here is a copy of my ldap.conf file 

```
#
# LDAP Defaults
# See ldap.conf(5) for details
# This file should be world readable but not world writable.

#BASE	dc=example,dc=com
#URI	ldap://ldap.example.com ldap://ldap-master.example.com:666

#SIZELIMIT	12
#TIMELIMIT	15
#DEREF		never
TLS_REQCERT	demand
```

is there a way to define or provide cert file within my defined script scope to eliminate system/OS dependencies especially around certs.

**Comment by chakrapani123** [comment]
here are steps followed to add cert:

```
openssl s_client -showcerts -host  example.com -port 636 > certs.crt
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain certs.crt
```

i have ran the script both as local user as well as root to address any user profile issues

**Comment by gheeres** [comment]
The activedirectory module is just a wrapper around the ldapjs library to support Microsoft specific extensions. So you can pass custom configuration and settings for ldapjs through the constructor / config object.

When creating your ad object, try the following:

```javascript
var config = { 
  url: 'ldaps://example.com:636',
  baseDN: 'OU=Service Accounts,OU=XXX,OU=XXX,DC=xXX,DC=XXXX,DC=XXX',
  username: 'abcdefff',
  password: 'BBBBYYY',
  tlsOptions: {
    rejectUnauthorized: false
  }
};
```
For more information about the **tlsOptions**, see the node.js [TLS documentation](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback). In the node.js documentation, they provide an example on providing a certificate authority.

Obviously, you won't want to leave that enabled and you'll want to specify a certificate chain, but you should be able to verify if things are working.

**Comment by chakrapani123** [comment]
this works ..with only CN in username but not email in username field...this might be a challenge as most ppl may not even know their CN ..i tried finduser with email in principal ( might be wrong )..with following snippet and obviously it errored out. 

```javascript
ad.findUser(userPrincipalName, function(err, user) {
  if (err) {
    console.log('ERROR: ' +JSON.stringify(err));
    return;
  }

  if (! user) console.log('User: ' + userPrincipalName + ' not found.');
  else console.log(JSON.stringify(user));
});
```

**Comment by gheeres** [comment]
The findUser method internally will build the query string as follows:

```javascript
/**
 * Gets the ActiveDirectory LDAP query string for a user search.
 *
 * @private
 * @param {String} username The samAccountName or userPrincipalName (email) of the user.
 * @returns {String}
 */
function getUserQueryFilter(username) {
  log.trace('getUserQueryFilter(%s)', username);
  var self = this;

  if (! username) return('(objectCategory=User)');
  if (isDistinguishedName.call(self, username)) {
    return('(&(objectCategory=User)(distinguishedName='+parseDistinguishedName(username)+'))');
  }

  return('(&(objectCategory=User)(|(sAMAccountName='+username+')(userPrincipalName='+username+')))');
}
```

It will take either a DN, userPrincipalName or sAMAccount Name.

**Comment by gheeres** [comment]
When you make the call, what is the value of userPrincipalName that you are attempting to query? If you are attempting to build an LDAP search filter (i.e. userPrincipalName=joe@domain.com), then it won't work.

**Comment by gheeres** [comment]
If you prefer to do that manually, you can use the find() method which expects an ldap search filter to be specified.

**Comment by chakrapani123** [comment]
seems to be a disconnect in our viewpoints..let me try to put it differently..

username in ur authenticate(username, password, callback) - as per my understanding is CN and it worked that way for me 

UPN(userprincipalname which usually is email with domain in it like example@domain.com which in my case is my enterprise mail id (..i might be wrong) but i am just referring to http://www.morgantechspace.com/2014/04/samaccountname-vs-userprincipalname.html

sAMAccountName is just loginid or networklogin ... I am not a windows expert and apologize for confusion..but just trying to understand if there is a way to connect CN which works for authenticate with my enterprisemail id or loginid as i have tried various combinations of 

find & finduser and i am getting undefined error.

find works with ldapsearchfilter  for "*abc*" or wild-search but if i provide my email id in search string it errors out. 

all I am trying to do is to use my email ID instead of CN/first&lastname to authenticate users .

**Comment by chakrapani123** [comment]
was able to resolve it thanks

**Comment by vishalpatidar00789** [comment]
I am facing the same eror: {"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"} after importing all certificates. Please help me! thanks in advance
