### ISSUE TITLE
How can I receive the full AD object with all the attributes not just the few from the examples?

### ISSUE THREAD

**Issue by SelfDevTV** [gheeres/node-activedirectory#207]
Hi guys,

I'm using this package right now and it works perfectly. 
The one thing I'm missing is to receive the full user object(s). 
I want to have more attributes then just the few from the example (samAccountName, mail, ...). 

Is this possible or will it get added in a future update? 
Am I just missing something? :D

Thank you guys! Great work at maintainers!

**Comment by SilvaLA59** [comment]
Hi @SelfDevTV , did find how to receive the full user object?
