### ISSUE TITLE
Get all groups of OU

### ISSUE THREAD

**Issue by oz81** [gheeres/node-activedirectory#27]
Hi, 

list of all OU  - 

``` javascript
ad.find('objectClass=organizationalUnit',function(err, ldapResults) {
  //ldapResults.other => all OUs 
}
```

I have a list of OUs and I want to find all groups that belong to specific OU

**Comment by delcon** [comment]
Has this issue ben solved? I also need to find all users in one OU.
Is there any example that I can follow?
