### ISSUE TITLE
authenticate with uppercase letters in password

### ISSUE THREAD

**Issue by GiladShoham** [gheeres/node-activedirectory#30]
hi,
i don't know why, but when i try to use authenticate function and the user have uppercase letters on his password i always get a credentials error.

```
{
    "dn": "",
    "code": 49,
    "name": "InvalidCredentialsError",
    "message": "80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db0\u0000"
}
```

**Comment by blissdev** [comment]
@gheeres I get the error mentioned here even with userPrincipalName style usernames. Is that to be expected, or am I doing something wrong? Basically if the credentials provided are valid, it succeeds with no error, but if the credentials are invalid I get that `InvalidCredentialsError` instead of auth just being false, which is a bit confusing to me.

**Comment by gheeres** [comment]
If the authentication fails, the LDAP server will return an exception (i.e. an error). The code just passes that exception back to the client and returns 'false' in the 'auth' (or second) parameter.

Here is the relevant code from the module:

```javascript
  client.bind(username, password, function(err, result) {
    if (err) {
      log.warn('%s. Error: %s', message, err);
      return(callback(err, false));
    }

    log.info(message);
    return(callback(err, true));
  });
```

Basically if your 'err' contains anything or 'auth' is not true, then you have to assume that authentication failed. 'err' hopefully will contain an exception that will tell you more about WHY it failed.

If you don't want to worry about the 'err', you can just check the 'auth' varlable and ignore the 'err' parameters. For example:

```javascript
if (ad.authentication(username, password, function(err, auth) {
  if (! auth) {
    console.log('User NOT authenticated');
    return;
  }
  console.log('User authenticated');
});
```

**Comment by blissdev** [comment]
@gheeres Thanks for the quick response! That was helpful.
