### ISSUE TITLE
question - test base DN configuration

### ISSUE THREAD

**Issue by GiladShoham** [gheeres/node-activedirectory#31]
hi,
i have some test configuration method on the client.
which take the configuration and try to authenticate.
the problem is the authenticate only get user and password so i can't validate the base dn.
which means the test pass ok, but when the user try to search users/groups he can't find anything.
is there anyway to validate also the base dn?

Thx.

**Comment by dorrotman** [comment]
Important note: Not all domains support anonymous binds.

You have to make sure the IT person opens this up to perform this query.
I'm looking for a way to detect the Base DN automatically and stumbled upon this thread, yet in my scenario I cannot count on my customers opening up anonymous access.
