### ISSUE TITLE
How can I search by objectGUID / binary filters?

### ISSUE THREAD

**Issue by CKarper** [gheeres/node-activedirectory#61]
I've been trying every which way to find users by a saved objectGUID, but nothing seems to be working.

I've tried filters using the RFC 2254 binary string format (which works in my LDAP test tools) and I get no result.   

MS suggests binding to an ldap:://server/<GUID=guid> format to get info, but I couldn't figure out how to make that work either.    

Is this a bug or some hole in my understanding of how things work?   Either way, a fix would be most helpful.  :-)

**Comment by gheeres** [comment]
The ActiveDirectory library is a wrapper around [ldapjs](http://ldapjs.org/). The [EqualityFilter](http://ldapjs.org/filters.html) in ldapjs, which attempts to parse binary, was overhauled in 0.7.2 (current github version). The new EqualityFilter allows you to pass binary values. The following code is a working example:

```javascript
var filters = require('ldapjs').filters;

// GUID Format = [3][2][1][0]-[5][4]-[7][6]-[8][9]-[10][11][12][13][14][15]
var objectGUID = '4e1a5921-46d3-4180-9804-49e413f7dc83';
var objectGUIDBuffer = new Buffer([ 0x21, 0x59, 0x1a, 0x4e, 0xd3, 0x46, 0x80, 0x41, 0x98, 0x04, 0x49, 0xe4, 0x13, 0xf7, 0xdc, 0x83 ]);

var opts = {
  filter : new filters.EqualityFilter({
    attribute: 'objectGUID',
    value: objectGUIDBuffer 
  })
};
activeDirectory.find(opts, function(err, results) {
  if (err) {
    console.log('ERROR: ' + err);
    return;
  }
  if (results != null) {
    console.log(results);
  }
});
```
Note: The above code DOES NOT work with the current npm release (0.7.1).

Based on the RFC you specified, in order to query the objectGUID (4e1a5921-46d3-4180-9804-49e413f7dc83), you would use the following query:

```
(objectGUID=\21\59\1a\4e\d3\46\80\41\98\04\49\e4\13\f7\dc\83)
```

However, that currently doesn't work with either the current version of ldapjs (0.7.1) or the github version. You might want to look upstream for additional help.

**Comment by CKarper** [comment]
Yeah, I've tried every permutation of that I could.   I reordered the bytes for the RFC style filter, to no avail.    

I can't pass in filters as you show at all.   Even a simple non-binary filter doesn't work.  I get 
TypeError: options.filter (Filter) required.

Should at least that be supported?

**Comment by CKarper** [comment]
I must be missing something...   ldapjs is still on 0.7.1 at this url: https://github.com/mcavage/node-ldapjs.

I've looked through all branches, and I don't see a 0.7.2 mentioned anywhere.

**Comment by gheeres** [comment]
Even though the version is still at 0.7.1, it differs from the npm release. 

I manually updated ldapjs under activedirection/node_modules to the latest github version.

You want to checkout the GITHUB version of [ldapjs](https://github.com/mcavage/node-ldapjs) to the following folder:

```
node_modules/activedirectory/node_modules/ldapjs
```

But doing that, doesn't really solve the problem. This looks to be an upstream ldapjs issue.

**Comment by gheeres** [comment]
See the following upstream issue:

https://github.com/mcavage/node-ldapjs/issues/218

**Comment by CKarper** [comment]
This ldapjs direct code (based off the sample code in the guide) works:
```javascript

var ldap = require('ldapjs');
var util = require('util');

ldap.Attribute.settings.guid_format = ldap.GUID_FORMAT_B;

var client = ldap.createClient({
    url: 'ldap://<SERVER>',
    bindDN: '<USERNAME>',
    bindCredentials: '<PASSWORD>'
});

var objectGUIDBuffer = new Buffer([ 0x9a, 0xdb, 0x58, 0x1d, 0x8b, 0xc3, 0x6e, 0x4e, 0xb9, 0x77, 0x11, 0x89, 0x9b, 0x22, 0x0f, 0xb9 ]);

var myFilter = new ldap.filters.EqualityFilter({
    attribute: 'objectGUID',
    value: objectGUIDBuffer
});

var entries = [];

client.search('dc=dev,dc=<COMPANY>,dc=com', {
        filter: myFilter,
        scope: 'sub',
        attributes: [ 'dn', 'cn', 'objectGUID', 'objectSid', 'displayName', 'userPrincipalName', 'mail', 'description'],
    }, function (err, res) {
        if (err) {
            console.log(err);
            console.log(err.stack);
            return;
        }

        res.on('searchEntry', function (entry) {
            entries.push(parseEntry(entry));
        });
        res.on('searchReference', function (referral) {
            //console.log('referral: ' + referral.uris.join());
        });
        res.on('error', function (err) {
            console.log('error: ' + err.message);
            process.exit(1);
        });
        res.on('end', function (result) {
            if (result.status !== 0) console.log('status: ' + result.status);
            if (entries.length > 0)  console.log(util.inspect(entries));
            process.exit();
        });
    }
);

function parseEntry(entry) {
    var obj = {};
    for (var index in entry.attributes) {
        var attr = entry.attributes[index];
        if (attr.vals.length === 1) {
            obj[attr.type] = attr.vals[0];
        }
        else {
            obj[attr.type] = attr.vals;
        }
    }
    return obj;
}
```

Running that same filter through node-activedirectory with the code you posted does not.   I get the aforementioned `ERROR: TypeError: ber (BerWriter) required`.

Could this be the result of an upstream change that's incompatible with this libs code?  I would follow up with them if I could repro this using only ldapjs code, but it seems to be closer to home to me.   I'll look myself through the ad lib code and see if I can't find it, but I'm still new so it may take some time.

Thanks for your time on this. :+1:

**Comment by gheeres** [comment]
In order for the code that I posted to work, you MUST manually update the underlying ldapjs libraries that activedirectory has a dependency on. Then in that folder, you'd want to run

```
npm update
```

To update all of the dependencies, etc.

**Comment by gheeres** [comment]
The problem MIGHT be due to you including a different ldapjs library, even if they are the same version, which makes the object incompatible. For my testing, I was using personal unit tests within my activedirectory source.

**Comment by gheeres** [comment]
Try modifying lib/activedirectory.js as follows:

```diff
index 28996ea..178fb1c 100755
--- a/lib/activedirectory.js
+++ b/lib/activedirectory.js
@@ -1717,4 +1717,5 @@ ActiveDirectory.prototype.getRootDSE = function getRootDSE(url, attributes, call
   });
 };

+ActiveDirectory.prototype.filters = ldap.filters;
 module.exports = ActiveDirectory;
```

Then you can access the filters like:

```javascript
var activeDirectory = require('activedirectory');

var filters = activeDirectory.filters;
var opts = {
  filter : new filters.EqualityFilter({
    attribute: 'objectGUID',
    value: objectGUIDBuffer
  })
};
activeDirectory.find(opts, function(err, results) {
  if (err) {
    console.log('ERROR: ' + err);
    return;
  }
  if (results != null) {
    console.log(results);
  }
});
```

This works for me.

**Comment by CKarper** [comment]
Remove that `.prototype` and that works!  I assume that should be accessed as a static.

That pesky inheritance chain was the issue I guess.  That was unexpected in JS, but it makes sense.

I'm submitting a [pull request](https://github.com/gheeres/node-activedirectory/pull/63) to expose the filters.

**Comment by gheeres** [comment]
Merged / closed. Thanks

**Comment by GiladShoham** [comment]
I have also encouraged this problem and I solved it without update the ldapjs version.
I have a lot of examples working on production for few months.
if it still relevant, tell me and I will post some examples.

**Comment by kevinhikaruevans** [comment]
I was having a similar issue, but I solved it a bit differently.

I just used `entryParser` and wrote a small little function to convert the buffer into Microsoft's (or is it an RFC definition) GUID format, like such:

    entryParser: function (entry, raw, callback){
      if (raw.hasOwnProperty("objectGUID")){
        entry.objectGUID = bufferToGUID(raw.objectGUID);
      }

      callback(entry);
    }

```
function bufferToGUID(buffer) {
  var s, hex = Array.prototype.map.call(buffer, function(value) {
    s = (value & 0xFF).toString(16);
    return value < 0xF ? ('0' + s) : s;
  });

  return [
    '<GUID=',
    hex[3],
    hex[2],
    hex[1],
    hex[0],
    '-',
    hex[5],
    hex[4],
    '-',
    hex[7],
    hex[6],
    '-',
    hex[8],
    hex[9],
    '-',
    hex[10],
    hex[11],
    hex[12],
    hex[13],
    hex[14],
    hex[15],
    '>'
  ].join('');
}
```

Then, to find the user, I just used:

```
  ad.findUser(user.objectGUID, function(err, results) {
    console.log(err, results);
  })
```
