### ISSUE TITLE
Confidentiality Error 

### ISSUE THREAD

**Issue by pratik1490** [gheeres/node-activedirectory#64]
While connecting to secure server, I am getting error (Confidentiality Error ). To solve this I tried to create https node server , but still its the same error.

**Comment by gheeres** [comment]
Can you provide an example of your configuration / code? Also, please include the full stack / dump trace if one is available.

**Comment by pratik1490** [comment]
As this part of internal network of company, I cant provide code or any
configuration.


​
This is the only error I am getting.

Thanks
Pratik

On Wed, Feb 18, 2015 at 1:03 PM, George Heeres <notifications@github.com>
wrote:

> Can you provide an example of your configuration / code? Also, please
> include the full stack / dump trace if one is available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gheeres/node-activedirectory/issues/64#issuecomment-74947254>
> .
>



-- 
Thanks and Regards
Pratik Bhatt
+1 619 735 8851
www.pratikbhatt.info

**Comment by gheeres** [comment]
Sorry, unless I can replicate the error you are receiving, I can't really help. 

In order to do that, I need more information. In particular, I need to know how you are trying to connect (i.e. your connection string) and then what function(s) you're trying to execute which are generating the error.

By all means, please obfuscate the host/server name and other confidential information in your sample code. But at a minimum, I need to get an "idea" about what you're trying to do so that I can write a test condition to replicate it.

**Comment by pratik1490** [comment]
var ActiveDirectory = require('activedirectory');
var ad = new ActiveDirectory({ url: 'server address',
                               baseDN: 'baseDN  ',
                               username: 'username',
                               password: 'password',
                               attributes:{
                                  inetOrgPerson: [ 'uid
','employeeType','groupMembership']
                               }
                           });

 ad.authenticate("username", "password", function(err, auth) {
   if (err) {
     console.log('ERROR: '+ JSON.stringify(err));
   }
   else{
      if (auth) {
        console.log("Is Authenticated");

        ad.findUser("username",function(err,user){
        console.log(user);
      });

      }
      else {
        console.log('Authentication failed!');
      }
    }
 });


On Wed, Feb 18, 2015 at 1:32 PM, George Heeres <notifications@github.com>
wrote:

> Sorry, unless I can replicate the error you are receiving, I can't really
> help.
>
> In order to do that, I need more information. In particular, I need to
> know how you are trying to connect (i.e. your connection string) and then
> what function(s) you're trying to execute which are generating the error.
>
> By all means, please obfuscate the host/server name and other confidential
> information in your sample code. But at a minimum, I need to get an "idea"
> about what you're trying to do so that I can write a test condition to
> replicate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gheeres/node-activedirectory/issues/64#issuecomment-74952319>
> .
>



-- 
Thanks and Regards
Pratik Bhatt
+1 619 735 8851
www.pratikbhatt.info

**Comment by gheeres** [comment]
Thanks.

That helps, except I really need to know what port you are using. Active Directory has a number of different ports that you can talk to. Go ahead and obfuscate everything except the port and uri identifier (i.e. ldap://, ldaps://, etc.). 

For example:

```javascript
url: 'dc1.domain.com:636'
```

**Comment by pratik1490** [comment]
ldap://dc1.domain.com:389

On Wed, Feb 18, 2015 at 2:09 PM, George Heeres <notifications@github.com>
wrote:

> Thanks.
>
> That helps, except I really need to know what port you are using. Active
> Directory has a number of different ports that you can talk to. Go ahead
> and obfuscate everything except the port and uri identifier (i.e. ldap://,
> ldaps://, etc.).
>
> For example:
>
> url: 'dc1.domain.com:636'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gheeres/node-activedirectory/issues/64#issuecomment-74958888>
> .
>



-- 
Thanks and Regards
Pratik Bhatt
+1 619 735 8851
www.pratikbhatt.info

**Comment by gheeres** [comment]
Unrelated to your problem, the way you've specified the attributes is invalid.

```javascript
attributes:{
  inetOrgPerson: [ 'uid','employeeType','groupMembership']
}
```

That should be:
```javascript
attributes:{
  user: [ 'uid','employeeType','groupMembership']
}
```

When are you getting the error? On the 'authenticate' or the 'findUser'. I ran the code you specified without error. So it's likely your AD server has some type of restrictions. 

Can you talk with your network admin to find out what is required (i.e. SSL, TLS, etc.) and what port they recommend to connect to? I'm going to "guess" you need to use SSL / TLS.

**Comment by pratik1490** [comment]
Yeah they told me to use SSL, just got email from them. And so I created
https node.js server. But still the issue is same. Can you suggest me any
another way to create or use SSL connection.

On Wed, Feb 18, 2015 at 2:32 PM, George Heeres <notifications@github.com>
wrote:

> Unrelated to your problem, the way you've specified the attributes is
> invalid.
>
> attributes:{
>   inetOrgPerson: [ 'uid','employeeType','groupMembership']
> }
>
> That should be:
>
> attributes:{
>   user: [ 'uid','employeeType','groupMembership']
> }
>
> When are you getting the error? On the 'authenticate' or the 'findUser'. I
> ran the code you specified without error. So it's likely your AD server has
> some type of restrictions.
>
> Can you talk with your network admin to find out what is required (i.e.
> SSL, TLS, etc.) and what port they recommend to connect to? I'm going to
> "guess" you need to use SSL / TLS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gheeres/node-activedirectory/issues/64#issuecomment-74962812>
> .
>



-- 
Thanks and Regards
Pratik Bhatt
+1 619 735 8851
www.pratikbhatt.info

**Comment by gheeres** [comment]
You need to provide the node.js [TLS](http://nodejs.org/api/tls.html) options. These options can be passed in your configuration object.

```
var ad = new ActiveDirectory({ 
  url: 'ldaps://dc1.domain.com',
  tlsOptions: {
    rejectUnauthorized: false
  },
  ...
});
```

A node.js https server wouldn't be used in the transaction.

**Comment by pratik1490** [comment]
Thank you for your help.

On Wed, Feb 18, 2015 at 2:46 PM, George Heeres <notifications@github.com>
wrote:

> You need to provide the node.js TLS <http://nodejs.org/api/tls.html>
> options. These options can be passed in your configuration object.
>
> var ad = new ActiveDirectory({
>   url: 'ldaps://dc1.domain.com',
>   tlsOptions: {
>     rejectUnauthorized: false
>   },
>   ...
> });
>
> A node.js https server wouldn't be used in the transaction.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gheeres/node-activedirectory/issues/64#issuecomment-74964993>
> .
>



-- 
Thanks and Regards
Pratik Bhatt
+1 619 735 8851
www.pratikbhatt.info
