### ISSUE TITLE
npm version log.info exception

### ISSUE THREAD

**Issue by GiladShoham** [gheeres/node-activedirectory#67]
hi,
i saw that the npm version still contain an old code in line 
1037 - ActiveDirectory.prototype.userExists function
log.info('"%s" %s exist.', username, (result != null) ? 'DOES' : 'DOES NOT');
instead of 
log.info('"%s" %s exist.', username, (user != null) ? 'DOES' : 'DOES NOT');

the code in the git is updated but the npm version isn't.
maybe it worth to make a new npm version because it make this function to not work

**Comment by gheeres** [comment]
That was merged with the following c
commit: 4477f436bdf08f0f6c4f986f1e19c5c57c94eef1

That was included with the v0.6.2 release. NPM is currently at v0.6.3. I just pulled the most recent npm release and the commit / patch is included.

You likely have your package.json dependency hard coded to pull a specific / older version. Check what version you have in your node_modules.
