### ISSUE TITLE
sizeLimit parameter does not return limited results

### ISSUE THREAD

**Issue by dorrotman** [gheeres/node-activedirectory#81]
Hi,
I encountered an issue with the parameter, please see this description:

Expected behavior: The sizeLimit parameter will be used to limit the amount of results. (Please correct me if I'm wrong here...)
Actual behavior: An error is thrown an no results are outputted at all.

On a domain with a huge amount of users (mine has 50k), it is impossible to not limit the results. I need to choose to either get 0 or infinity results, which both do not serve my need.

It seems that ldap.js by itself does support this limiting, however the processing done by this package doesn't happen when the error is thrown by ldap.js.
See this sample scenario:

```javascript
var ActiveDirectory = require('activedirectory');

function query(ldapQuery) {
    var client = new ActiveDirectory({
        url: 'ldap://1.1.1.1:389',
        baseDN: 'CN=Users,DC=mydomain,DC=local',
        username: 'CN=Administrator,CN=Users,DC=mydomain,DC=local',
        password: '****'
});

    var searchQuery = '(&(|(cn=*' + ldapQuery.query + '*)(sAMAccountName=*' + ldapQuery.query + '*))(&(objectCategory=person)(objectClass=user)))';
    console.log(searchQuery);
    var currentQuery = {
        scope : 'sub', 
        filter : searchQuery,
        sizeLimit : 300 // BUG HERE: does not work as expected. Remove this line to get any results.
    }

    client.find(currentQuery, function(err, result) {
          if (err) {
            console.log('ERROR: ' + JSON.stringify(err));
          }
          if(result) {
            console.log('got result!');
          }
          if(!result) {
            console.log('no result!');
          }
          process.exit(1);
        });
}

var myQuery = {
                    query : 'a',
                };
query(myQuery);
```

**Comment by gheeres** [comment]
I believe issue #47 is related to this. What is the error you are receiving?

**Comment by dorrotman** [comment]
Hi George, thanks for the response.
I am getting a SizeLimitExceededError.
My case is much simpler than #47, I just want to get the user and group details without any memberships, as the code above shows.

Your solution to that issue was:
1.) Run a simple / minimal query to find the users that match. 
2.) Truncate that list to the number you want (i.e. 20).

However, I cannot control the search input or the amount of matches in the Active Directory, so there is no simple or minimal query. If I don't set a limit, I may get an astronomical amount of results. The query will take too much time so for the user it would time out, and processing would be much heavier.
To make a long story short:
1. If I'm misusing the package, then what is the expected behavior of using this field?
2. If I'm using the package correctly, then the same processing needs to be applied to results that come in until the error, as would happen if the result events would end gracefully. 

I can start using ldap.js directly instead, that solves my problem. However, I think this package has added value and I want to address this issue so I can use it as I originally intended.

Thanks,
Dor.

**Comment by gheeres** [comment]
Please apply the following diff and let me know the results:

```diff
index c039d88..4fb2df0 100755
--- a/lib/activedirectory.js
+++ b/lib/activedirectory.js
@@ -479,14 +479,15 @@ function search(baseDN, opts, callback) {
   /**
    * Occurs when a client / search error occurs.
    * @param {Object} err The error object or string.
+   * @param {Object} res The optional server response.
    */
-  function onClientError(err) {
-    client.unbind();
+  function onClientError(err, res) {
     if ((err || {}).name === 'SizeLimitExceededError') {
-      if (callback) callback(err, results);
+      onSearchEnd(res);
       return;
     }

+    client.unbind();
     log.error(err, '[%s] An error occurred performing the requested LDAP search on %s (%j)',
               (err || {}).errno || 'UNKNOWN', baseDN, opts);
     if (callback) callback(err);
@@ -533,7 +534,7 @@ function search(baseDN, opts, callback) {

     res.on('searchEntry', onSearchEntry);
     res.on('searchReference', onReferralChase);
-    res.on('error', onClientError);
+    res.on('error', function(err) { onClientError(err, res); });
     res.on('end', function(result) {
       isDone = true; // Flag that the primary query is complete
       onSearchEnd(result);
```

The sample code I used for testing is:

```javascript
var limit = 5;
var filter = '(&(cn=Smith*)(objectcategory=person))';
var opts = {
  sizeLimit: limit,
  filter: filter
};

ad.findUsers(opts, function(err, users) {
  if (err) {
    console.log('ERROR: ' + err + '. Results: ' + (users || []).length);
    return;
  }

  console.log('findUsers('+filter+')['+limit+']='+JSON.stringify(users));
});
```

**Comment by dorrotman** [comment]
Tested it with my code and it works well: Returns limited size results quickly, as needed. 
One thing to note is that if the sizeLimit is above 1000, then it is not taken into consideration. In this case, the caller could still get *infinity* results.
(I'm guessing 1000 records is a page size for the LDAP query?)

Thanks!
Dor.

**Comment by gheeres** [comment]
Yes. ActiveDirectory has a limit configured on the server of 1000 results by default. Once that limit is reached, the ldap paging controls take effect. 

I'll get the fix merged and push a new version.

**Comment by dorrotman** [comment]
Thanks! :smiley:
