### ISSUE TITLE
Readme page has a couple of errors in example for find

### ISSUE THREAD

**Issue by buchs-kevin** [gheeres/node-activedirectory#83]
The example for find contains an assignment to "results" but then later references "result". Also, there are three references to "_.each". I'm not very proficient in node and js, but that throws a error for me, with "_" undefined. 

As long as I am sharing suggestions, I think the page would really benefit with a full example showing the assignment of config before the calling ActiveDirectory(config).

**Comment by gheeres** [comment]
Merged pull request f56448844e38bd3a89fd30e881824f665fbc6d34
