### ISSUE TITLE
Question : Need to know how to query and obtain password from Active Directory.

### ISSUE THREAD

**Issue by facascante** [gheeres/node-activedirectory#87]
Hi,

there is a radius server using active directory to implement mschapv2 authentication.
and base on mschapv2 documentation the radius server is able to get password from active directory.

but we dont know how is it possible, though some research says you cant get password, some research say you can if you set password to clear-text or assigned proper permission.

if someone can help us to find out how to query those password in active directory same way the microsoft radius server does. as we planning to do the same mschapv2 implementation using our own code in nodejs.

**Comment by gheeres** [comment]
The password of a user in Active Directory is stored in encrypted format. 

From my cursory research, the "Store passwords using reversible encryption" seems to have been modified or removed with Windows 2008 and later? Here is some additional reading that I found:

http://blog.teusink.net/2009/08/passwords-stored-using-reversible.html
http://blog.degree.no/2012/07/active-directory-password-decryption-yes-it-can-be-done/

**Comment by facascante** [comment]
i see

thank you
