### ISSUE TITLE
Using Git tags for version

### ISSUE THREAD

**Issue by toymachiner62** [gheeres/node-activedirectory#88]
I highly suggest that you start using [Tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) in your project. I'm currently on node-activedirectory 0.6.2 and I get an error with a line number, but since you didn't use tags, i can't trace back to that line number b/c you have 1 branch "master" which may have been updated since version 0.6.2.

**Comment by gheeres** [comment]
Thank you for the suggestion / tip. I've been meaning to go back and add tags but I haven't found the time or opportunity.

9676230a60befaa399d6c43be24f2a673678cda6 was the v0.6.2 release.

**Comment by gheeres** [comment]
Tags added as requested.
