### ISSUE TITLE
password

### ISSUE THREAD

**Issue by yosser22** [gheeres/node-activedirectory#92]
Hi everybody, 
I'm new to nodejs. I'm using this module to authenticate users for a Microsoft Active Directory. I'm not sure how secure the communication with the active directory is. Are the passwords sent in plaintext to the active directory ???
Thank you!!!

**Comment by improvisio** [comment]
This IMHO depends on the protocol you're using. Stick with LDAP and you should be good to go. However latest release of ldap-js (a dependency of this project) has an issue which is only solved in current master. If you use a fork I've made recently, you will be fine. Look for repositories in "improvisio software" company.



5. 7. 2015 13:43, 13:43, yosser22 <notifications@github.com> napsal/a:

**Comment by yosser22** [comment]
So sorry but I'm really a beginner. The URL of the active directory is  'ldap://domain.de'. Does it mean that the communication is secure and the passwords are not transmitted in plaintext??
thank you :)

**Comment by improvisio** [comment]
No, this way i'm afraid its not secure. Try switching to ldaps://same-url (default port is 636) and if it works, you're safe ;-)



5. 7. 2015 13:59, 13:59, yosser22 <notifications@github.com> napsal/a:

**Comment by yosser22** [comment]
Thank you !!!!
