### ISSUE TITLE
ERROR: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}

### ISSUE THREAD

**Issue by dq100** [gheeres/node-activedirectory#93]
Hello,

my Code fetches all Users from an AD-Group and then tests, if the user is in another group.After that it saves the user in mongoDB. 
It is working well but sometimes it crashes with this error message:

ERROR: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
D:\surveillance\Backend\node_modules\activedirectory\node_modules\async\lib\asyn
c.js:38
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at D:\surveillance\Backend\node_modules\activedirectory\node_modules\async\l
ib\async.js:38:31
    at D:\surveillance\Backend\node_modules\activedirectory\lib\activedirectory.
js:720:13
    at D:\surveillance\Backend\node_modules\activedirectory\lib\activedirectory.
js:690:7
    at onSearch (D:\surveillance\Backend\node_modules\activedirectory\lib\active
directory.js:530:21)
    at onAcquire (D:\surveillance\Backend\node_modules\activedirectory\node_modu
les\ldapjs\lib\client\pool.js:203:14)
    at f (D:\surveillance\Backend\node_modules\activedirectory\node_modules\ldap
js\node_modules\pooling\node_modules\once\once.js:16:25)
    at onCreatedClient (D:\surveillance\Backend\node_modules\activedirectory\nod
e_modules\ldapjs\node_modules\pooling\lib\pool.js:260:25)
    at createCallback (D:\surveillance\Backend\node_modules\activedirectory\node
_modules\ldapjs\node_modules\pooling\lib\pool.js:426:25)
    at Client.<anonymous> (D:\surveillance\Backend\node_modules\activedirectory\
node_modules\ldapjs\lib\client\pool.js:53:16)
    at Client.emit (events.js:107:17)
    at Socket.onError (D:\surveillance\Backend\node_modules\activedirectory\node
_modules\ldapjs\lib\client\client.js:176:12)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

In Addition the CPU load is at 100% while executing this Code.
My Code looks like this:

setInterval(function() {
	console.log('update users!');
	var groupNameUser = 'Dom-Surveillance-User';
	var groupNameAdmin = 'Dom-Surveillance-Admin';

	//reload User and Admin-User
	ad.getUsersForGroup(groupNameUser, function(err, users) {
		if (err) { return console.log('ERROR: ' +JSON.stringify(err));}
		if (! users) {return console.log('Group: ' + groupName + ' not found.');}
		else {
			users.forEach(function(singleUser){
				ad.isUserMemberOf(singleUser.dn, groupNameAdmin, function(err, isMember) {
					if (err) { return console.log('ERROR: ' +JSON.stringify(err));}
					
					console.log(singleUser.dn + ' admin:' + isMember);
					userModel.findOrCreate({personalId: singleUser.cn}, {
						firstName: singleUser.givenName,
		                lastName: singleUser.sn,
		                email: singleUser.mail,
		                ldapUser: true,
		                isUser: true,
		                isAdmin: isMember
					}, function(err, user){
						//Update Fields if the changed
						user.personalId=singleUser.cn;
		                user.firstName=singleUser.givenName;
		                user.lastName=singleUser.sn;
		                user.email=singleUser.mail;
		                user.isUser=true;
		                user.isAdmin=isMember;

		                //Save user
		                user.save(function(err){
		                	if(err){return console.log(err);}
		                });
					});
				});
			}); //foreach
		}
		return ;
	});
}, 300000);

Can you help me?
(Sorry for bad English)

**Comment by gheeres** [comment]
Looking at the error trace, we see that a socket exception occurred. This is likely the AD server disconnecting or timing out.

As it's currently implemented, calling [isUserMemberOf](https://github.com/gheeres/node-activedirectory#isUserMemberOf) is an "expensive" operation. It will actually enumerate all of the groups that a user belongs to. Since you're just looking for the members of the admin group, I would recommend to call [getUsersForGroup](https://github.com/gheeres/node-activedirectory#getUsersForGroup) for the admin group. Then you can just enumerate over those results doing your comparison. It will be much faster and more efficient.

**Comment by dq100** [comment]
Thanks for your reply,
i changed my function, and it looks like it doesn´t crash anymore.
