### ISSUE TITLE
 CERT_UNTRUSTED error 

### ISSUE THREAD

**Issue by yosser22** [gheeres/node-activedirectory#94]
Hi everybody,

I'm using node-activedirectory in order to authenticate user against AD "ldaps://url" using SSL. 
the SSL certificate that the domain controller (i.e. Active Directory) is using or returning to me
 is signed by a certificate authority that my machine trusts. 
When I test the authentication against the same AD using another application it works perfectly(same certification, same client, same AD, the application is not a nodejs application). 
It means that my machine trusts the certificate authority returned by the AD. (I can also see the certificate on the list of trusted certificates).
So now the problem is that  when I try the same in my nodejs application using the node-activedirectory modul, I'm getting a CERT_UNTRUSTED error !!!!
I think that the node-activedirectory doesn't recognize the certification although it is on the list of trusted certifications.
This error is driving me crazy. So if anyone has a suggestion, please help!

Thank you

**Comment by gheeres** [comment]
Closed as duplicate. See issue #14.
