### ISSUE TITLE
Timeouts specific to user account

### ISSUE THREAD

**Issue by thethomaseffect** [gheeres/node-activedirectory#98]
Okay, so this is __REALLY__ hard to debug and reproduce so my apologies but this is the best info I can provide.

Sometimes on our web app login attempts using node-activedirectory timeout, but the interesting thing is that these are specific to the user, so if another user on the same machine tries they can login just fine. Below is the console log for the failed attempt:

```
{"name":"ActiveDirectory","hostname":"91-D0S094186","pid":13396,"level":20,"msg":"Creating ldapjs client for ldap://domain.co.uk. Opts: {\"maxConnections\":20}","time":"2015-07-24T14:49:42.401Z","v":0}
{"name":"ActiveDirectory","hostname":"91-D0S094186","pid":13396,"level":50,"msg":"An unhandled error occured on bind at \"ldap://domain.co.uk\". Error: {\"code\":\"ETIMEDOUT\",\"errno\":\"ETIMEDOUT\",\"syscall\":\"connect\"}","time":"2015-07-24T14:50:03.409Z","v":0}
{"name":"ActiveDirectory","hostname":"91-D0S094186","pid":13396,"level":40,"msg":"Authentication failed for \"ldap://domain.co.uk\" as \"DOMAIN\\user01\" (password: \"********\"). Error: Error: connect ETIMEDOUT","time":"2015-07-24T14:50:03.410Z","v":0}
POST /auth/active-directory 500 21010.709 ms - 53
```

It's possible this isn't a bug with activedirectory or the underlying ldapjs but I thought I'd report it just in case it was. The fact it only affects certain accounts for a fixed period of time made me suspect it may not be an issue with our ldap server. The bug disappears after a certain amount of time, I've no idea right now if that's because the client created by ldapjs is discarded after that amount of time or it's our ldap server.

I'll try my best to provide any more information you might need.

**Comment by gheeres** [comment]
The ETIMEDOUT error is a network / server problem. Essentially, the server isn't responding to the request quick enough. I'd recommend putting up some performance monitors on your AD server(s).

**Comment by gheeres** [comment]
You can also try to "stress" test your server by writing a loop with the code in question. Probably don't want to run that during normal business hours...

**Comment by gheeres** [comment]
What is the code that runs in your "/auth/auth-directory"? In particular, what AD queries and method are being called?

**Comment by thethomaseffect** [comment]
Unfortunately we have no control over the AD server as we're quite a large organization. Stress testing isn't an option due to this as well.
The code running is simply the authenticate function used in the following way:

```javascript
 ad.authenticate(`${config.domainPrefix}${req.body.username}`,
    req.body.password, function(error, valid) {
    /// code handling the response
});
```

the ES6 template string simply resolves to DOMAIN\username nothing fancy. I haven't worked much with ad in the past so I thought it was really strange that the problem seemed to only affect a single account at a time (i.e. other users can login successfully on the same session on the users computer), do you have any idea why this would be? 

Is there a way I can pass a shorter timeout to the `authenticate`function?

**Comment by gheeres** [comment]
The ad.authenticate() function is the simplest functionality in the library. All it does is perform an LDAP bind against the server to verify credentials. 

>as we're quite a large organization

I use this code with an AD comprised of over 10,000 users, with heavily nested groups. One group (Students) actually has over 9000 members in it alone.

If you're NOT connected to your AD via a WAN (or other slow connection), you most likely have performance or scaling problems with your Active Directory infrastructure. I would check / ensure that the DC (domain controller) you're connecting to isn't your disaster recovery or offsite node (which typically would be going over a WAN). I'd also find out how many DCs you have in your organization.

**Comment by gheeres** [comment]
Closing due to user infrastructure / server problem. Don't believe it's related to active directory module. Please provide more information and sample and will reopen.
